#!/usr/bin/env sh

# Configure git defaults
git config --global user.name "jovyan"
git config --global user.email "jovyan@mybinder"

# Make temporary directories (these are ignored in .gitignore)
mkdir big_data output

# Download our large data file
wget https://osf.io/h2ubm/download -O big_data/hw_25000.csv